### ISSUE TITLE
Typo in readme

### ISSUE THREAD

**Issue by smjonas** [Djancyp/cheat-sheet#1]
Just wanted to let you know that the repo name in the installation section should be `cheat-sheet` instead of `cheet-sheet` :)

**Comment by smjonas** [comment]
Also (unrelated), the command `:CheatSH` is not defined for me. Maybe you should move the `plugin/cheatsh.vim` file to the `plugin/after` directory? Or use Neovim's API to define the autocommand directly in Lua.

**Comment by Djancyp** [comment]
Thanks for feedback
 -typo fixed also I have moved the cheatsh.vim to after folder.
